prooph_service_bus:
  command_buses:
    vending_command_bus:
      router:
        type: 'prooph_service_bus.command_bus_router'

  query_buses:
    vending_query_bus:
      router:
        type: 'prooph_service_bus.query_bus_router'

  event_buses:
    vending_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'
        # routes:
        #   'Prooph\ProophessorDo\Model\Todo\Event\TodoAssigneeWasReminded':
        #     - 'Prooph\ProophessorDo\ProcessManager\SendTodoReminderMailProcessManager'
        #
        #   'Prooph\ProophessorDo\Model\Todo\Event\TodoWasMarkedAsExpired':
        #     - 'Prooph\ProophessorDo\ProcessManager\SendTodoDeadlineExpiredMailProcessManager'
